/*
 * DO NOT MODIFY. This file is automatically generated during the pre-build
 *                step by the lib_search utility
 */

"E:\ti\simplelink_cc2640r2_sdk_1_35_00_33\source\ti\ble5stack\blelib\ctrl\cc2640_hci_pxxx.a"
"E:\ti\simplelink_cc2640r2_sdk_1_35_00_33\source\ti\ble5stack\blelib\ctrl\cc2640_ll_pxxx.a"
"E:\ti\simplelink_cc2640r2_sdk_1_35_00_33\source\ti\ble5stack\blelib\hci_tl\cc26xx_hci_tl_none.a"
"E:\ti\simplelink_cc2640r2_sdk_1_35_00_33\source\ti\ble5stack\blelib\host\cc26xx_att_pxxx.a"
"E:\ti\simplelink_cc2640r2_sdk_1_35_00_33\source\ti\ble5stack\blelib\host\cc26xx_gap_pxxx.a"
"E:\ti\simplelink_cc2640r2_sdk_1_35_00_33\source\ti\ble5stack\blelib\host\cc26xx_gatt_pxxx.a"
"E:\ti\simplelink_cc2640r2_sdk_1_35_00_33\source\ti\ble5stack\blelib\host\cc26xx_l2cap_pxxx.a"
"E:\ti\simplelink_cc2640r2_sdk_1_35_00_33\source\ti\ble5stack\blelib\host\cc26xx_profiles_pxxx.a"
"E:\ti\simplelink_cc2640r2_sdk_1_35_00_33\source\ti\ble5stack\blelib\host\cc26xx_smp_pxxx.a"
"E:\ti\simplelink_cc2640r2_sdk_1_35_00_33\source\ti\ble5stack\blelib\host\cc26xx_sm_pxxx.a"
